### ISSUE TITLE
The open-set evaluation

### ISSUE THREAD

**Issue by komejisatori** [nukezil/IOMatch#1]
Thanks for your excellent work and the code!
I am trying to run the IOMatch, and I found the current code only provides accuracy on the close-set test set.
Could you please tell me how to evaluate on the open-set test set using this code?

**Comment by nukezil** [comment]
Thank you for your interest in our work!
The code for open-set evaluation has been uploaded in [`evaluate.ipynb`](https://github.com/nukezil/IOMatch/blob/main/evaluate.ipynb). Please also check the updated README file for the link of extended testing data.

**Comment by komejisatori** [comment]
Thanks!
