### ISSUE TITLE
ImportError: cannot import name 'get_cifar' from 'semilearn.datasets.cv_datasets.cifar' (/hy-tmp/IOMatch/semilearn/datasets/cv_datasets/cifar.py)

### ISSUE THREAD

**Issue by honeysuckcle** [nukezil/IOMatch#3]
```
File "IOMatch/semilearn/datasets/cv_datasets/__init__.py", line 1, in <module>
    from .cifar import get_cifar, get_cifar_openset
ImportError: cannot import name 'get_cifar' from 'semilearn.datasets.cv_datasets.cifar' (IOMatch/semilearn/datasets/cv_datasets/cifar.py)
```
/semilearn/datasets/cv_datasets/cifar.py文件里没有get_cifar函数

**Comment by nukezil** [comment]
This function was used to get standard CIFAR-10/100 datasets (with no unlabled outliers in training) and was removed when we formated the released code. You may update your local repo to the latested version in which `import get_cifar` has been also removed.

Thanks for your interest! If there is any other problem, please feel free to let me know.

**Comment by honeysuckcle** [comment]
Thank you very much.
