### ISSUE TITLE
The open-set evaluation for openmatch

### ISSUE THREAD

**Issue by oyoycr** [nukezil/IOMatch#5]
Thanks for your excellent work and providing the code!
I'm trying to run IOMatch and found that you provided the open-set test code for IOMatch. Could you please provide the open-set test code for OpenMatch?

**Comment by nukezil** [comment]
Thanks for your interest! The open-set test code for OpenMatch has been included in the updated [evaluate.ipynb](https://github.com/nukezil/IOMatch/blob/main/evaluate.ipynb). Please refer to the `evaluate_open` func.

**Comment by oyoycr** [comment]
Thank you very much!!!
