### ISSUE TITLE
Inquiry about the model parameters for Open-Set SSL baselines

### ISSUE THREAD

**Issue by changwxx** [nukezil/IOMatch#6]
Hi! Thanks for your remarkable work and the meticulously crafted open-source code. Your efforts are truly appreciated.

I'm reaching out to inquire about the model parameters for Open-Set SSL baselines. Currently, as we follow your experimental setting, we are suggested to compare the AUROC for both seen and unseen outliers.

> [ICCV 2023] SSB: Simple but Strong Baseline for Boosting Performance of Open-Set Semi-Supervised Learning [[PDF]](https://arxiv.org/pdf/2311.10572.pdf) [[Code]](https://github.com/YUE-FAN/SSB)

A concurrent work SSB has shown that OpenMatch and T2T can acchieve fair performance in both inliers classification and outliers detection, as depicted in the following Table A. However, these findings seem to contradict the data presented in the IOMatch report in the following Table B. Upon closer examination, it's evident that there are notable differences in evaluation protocols, as summarized in the following Table C. 

**Table A**: SSB-reported data for OpenMatch and T2T, borrowing data from SSB in Table 8, 15, 16. (CIFAR-10, Inlier/outlier: 6/4, lables per samples: 25)
|  method   | accuracy (%) for inliers  |AUROC (%) for all outliers  | AUROC (%) for seen outliers  | AUROC (%) for unseen outliers|
|  ----  | ----  | ---- |---- |---- |
| OpenMatch  |54.88±2.33 |53.32±4.62 | 62.46±4.19 | 44.18±5.05 |
| T2T  |83.21±0.98 |44.79±17.26 | 34.90±27.50 | 54.68±7.01|

**Table B**: IOMatch-reported data OpenMatch and T2T, borrowing data from IOMatch in Table 1, 2, 6. (CIFAR-10, Inlier/outlier: 6/4, lables per samples: 25)
|  method   | recall rate for seen-class test  | balanced accuracy for open-set test |  balanced accuracy for inter-dataset open-set test |
|  ----  | ----  | ---- |---- |
| OpenMatch  | 43.63 ± 3.26 | 14.37 ± 0.05  | 20.31 ± 3.49 | 
| T2T  | 73.89 ± 1.55 | 50.57 ± 0.38 | 61.78 ± 0.89 |

 

**Table C**: Comparsion between SSB and IOMatch in evaluation protocols, where "I" indicates inliers, "SO" indicates seen outliers, "UO" indicates unseen outliers, "ALL={CIFAR10, CIFAR100, ImageNet, SVHN, LSUN}"
|  method   | test set | unseen outlier test set | evaluation metric | 
|  ----  | ----  | ---- | ---|
| IOMatch  |  3 cases: {I}/{I,SO}/{I,SO,UO} |SVHN, LSUN, synthetic Gaussian and uniform noise images |recall for {I} case, averaged K+1 recall for {I,SO}/{I,SO,UO} case| 
| SSB  | only 1 cases: {I,SO,UO} |remove corresponding train set from ALL | accuracy for I, AUROC for SO+UO/SO/UO| 

Nevertheless, we're expected to verify their performance under aligned evaluation protocols. Could you kindly provide the parameters for all your well-trained Open-Set SSL baseline models, including UASD, DS3L, MTCF, T2T, OpenMatch, and SAFE-STUDENT, for CIFAR10, CIFAR100, and IMAGENET30 datasets?

Given that your IOMatch is the first work to propose such a challenging experiment setting under labeled data scarcity, sharing these baseline model parameters will be greatly beneficial for the community to better follow your work.

Many thanks in advance! Looking forward to your reply.

**Comment by nukezil** [comment]
Hi! I'm sorry that we haven't saved all the trained baseline models, but I've just sent you the code I reimplemented via email. You can use them to train models and test them in the way you need.

**Comment by changwxx** [comment]
Thank you so much!
